version: '3.8'

services:
  discord-peter:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEFAULT_PROVIDER=${DEFAULT_PROVIDER}
      - TEXT_MODEL=${TEXT_MODEL}
      - VISION_MODEL=${VISION_MODEL}
      - REDIS_URL=redis://redis:6379
      - LOKI_URL=${LOKI_URL}
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    name: discord-peter-redis-data