apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discord-peter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "discord-peter.labels" . | nindent 4 }}
data:
  TEXT_MODEL: {{ .Values.config.textModel }}
  VISION_MODEL: {{ .Values.config.visionModel }}
  DEFAULT_PROVIDER: {{ .Values.config.defaultProvider }}