apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discord-peter.fullname" . }}-config
  labels:
    {{- include "discord-peter.labels" . | nindent 4 }}
data:
  TEXT_MODEL: {{ .Values.config.textModel | quote }}
  VISION_MODEL: {{ .Values.config.visionModel | quote }}
  DEFAULT_PROVIDER: {{ .Values.config.defaultProvider | quote }}
  REDIS_URL: {{ .Values.config.redisUrl | default (printf "redis://%s-redis-ha:6379" .Release.Name) | quote }}
  LOKI_URL: {{ .Values.config.lokiUrl | quote }}
  {{- if .Values.config.openaiBaseUrl }}
  OPENAI_BASE_URL: {{ .Values.config.openaiBaseUrl | quote }}
  {{- end }}
  {{- if .Values.config.ollamaUrl }}
  OLLAMA_URL: {{ .Values.config.ollamaUrl | quote }}
  {{- end }}
