apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discord-peter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "discord-peter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discord-peter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "discord-peter.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ printf "%s-redis-master" .Release.Name }} 6379; do
                echo "Waiting for Redis...";
                sleep 2;
              done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "discord-peter.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "discord-peter.fullname" . }}-config