apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-peter.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "discord-peter.labels" . | nindent 4 }}
type: Opaque
data:
  DISCORD_TOKEN: {{ .Values.secrets.discordToken | b64enc }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc }}