name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      tag:
        type: string
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64/v8
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ inputs.ref }}
          ghcr.io/${{ github.repository }}:${{ inputs.tag }}
        build-args: |
          VERSION=${{ inputs.ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max