name: Bump Chart Version

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true

jobs:
  bump-chart-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get current chart version
        run: |
          CHART_VERSION=$(yq e '.version' charts/discord-peter/Chart.yaml)
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install bump-my-version
        shell: bash
        run: pip install "bump-my-version==1.2.0"

      - name: Bump version
        id: bump
        shell: bash
        run: |
          echo "PREVIOUS_VERSION=$(bump-my-version show current_version)" >> $GITHUB_ENV
          bump-my-version bump patch --current-version=${{ env.CHART_VERSION }}
          if [[ $? -gt 0 ]]; then
            echo "BUMPED=false" >> $GITHUB_ENV
          else
            echo "BUMPED=true" >> $GITHUB_ENV
          fi
          echo "CURRENT_VERSION=$(bump-my-version show current_version)" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git add charts/discord-peter/Chart.yaml
          git commit -m "Bump version: ${{ env.PREVIOUS_VERSION }} → ${{ env.CURRENT_VERSION }} [skip ci]"
          git push origin ${{ inputs.ref }}
