name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    
concurrency:
  group: "cicd"
  cancel-in-progress: false

jobs:
  build-image-workflow:
    uses: ./.github/workflows/docker-build.yml

  test-chart-workflow:
    needs: build-image-workflow
    uses: ./.github/workflows/test-chart.yml

  release:
    needs: test-chart-workflow
    uses: ./.github/workflows/release-chart.yml

  deploy:
    needs: release
    uses: ./.github/workflows/deploy-chart.yml