name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/charts/**/Chart.yaml' # Don't run on version bump commits
      - '.github/**'
      - '.bumpversion.toml'
    
concurrency:
  group: "cicd"
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/release-chart.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    uses: ./.github/workflows/deploy-chart.yml
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      REDIS_STORAGE_CLASS: ${{ secrets.REDIS_STORAGE_CLASS }}
      REDIS_SUBPATH: ${{ secrets.REDIS_SUBPATH }}
