name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'charts/discord-peter/Chart.yaml'

jobs:
  build-image-workflow:
    uses: ./.github/workflows/docker-build.yml

  test-chart-workflow:
    needs: build-image-workflow
    uses: ./.github/workflows/test-chart.yml

  release-chart-workflow:
    needs: test-chart-workflow
    uses: ./.github/workflows/release-chart.yml