name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - '.bumpversion.toml'
    
concurrency:
  group: "cicd"
  cancel-in-progress: false

jobs:
  bump-version:
    uses: ./.github/workflows/bump-chart-version.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    needs: bump-version
    uses: ./.github/workflows/release-chart.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}