name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-image-workflow:
    uses: ./.github/workflows/docker-build.yml

  test-chart-workflow:
    needs: build-image-workflow
    uses: ./.github/workflows/test-chart.yml
