name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - './charts/**/Chart.yaml' # Don't run on version bump commits
      # - '.github/**'
    
concurrency:
  group: "cicd"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build-image.yml

  test:
    needs: build
    uses: ./.github/workflows/test-chart.yml

  release:
    needs: test
    uses: ./.github/workflows/release-chart.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    needs: release
    uses: ./.github/workflows/deploy-chart.yml
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}