name: Dependabot PR

on:
  pull_request_target:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '.github/**/*.yml'
      - 'charts/**'
    
concurrency:
  group: "test-dependencies"
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  test-app:
    uses: ./.github/workflows/test-node-app.yml
    with:
      ref: ${{ github.head_ref }}

  purge-old-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check if image tag exists
        id: check_tag
        run: |
          TAG="pr-${{ github.event.pull_request.number }}"
          echo "Checking for tag: $TAG"
          IMAGES=$(gh api "GET /users/${{ github.repository_owner }}/packages/container/${{ github.event.repository.name }}/versions" --jq ".[.metadata.container.tags[]" | grep "$TAG" || true)
          echo "Images found: $IMAGES"
          if [ -n "$IMAGES" ]; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Purge old image
        if: steps.check_tag.outputs.tag_exists == 'true'
        uses: chipkent/action-cleanup-package@v1.0.1
        with:
          package-name: ${{ github.event.repository.name }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GH_TOKEN }}

  build-image:
    needs: test-app
    if: always()
    uses: ./.github/workflows/build-image.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      tag: pr-${{ github.event.pull_request.number }}

  test-chart:
    needs: build-image
    uses: ./.github/workflows/test-chart.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      tag: pr-${{ github.event.pull_request.number }}

  bump-version:
    needs: test-chart
    uses: ./.github/workflows/bump-chart-version.yml
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  finalize:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Retag image
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull --platform linux/arm64 ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
          docker tag ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Approve PR
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && success() }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}