name: Dependabot PR

on:
  pull_request_target:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '.github/**/*.yml'
      - 'charts/**'
    
concurrency:
  group: "test-dependencies"
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  test-app:
    uses: ./.github/workflows/test-node-app.yml
    with:
      ref: ${{ github.head_ref }}

  purge-old-image:
    runs-on: ubuntu-latest
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.1
        with:
          package-name: ${{ github.event.repository.name }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GH_TOKEN }}

  build-image:
    needs: [test-app, purge-old-image]
    uses: ./.github/workflows/build-image.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      tag: pr-${{ github.event.pull_request.number }}

  test-chart:
    needs: build-image
    uses: ./.github/workflows/test-chart.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      tag: pr-${{ github.event.pull_request.number }}

  bump-version:
    needs: test-chart
    uses: ./.github/workflows/bump-chart-version.yml
    with:
      ref: ${{ github.head_ref }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  finalize:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Retag image
        uses: tinact/docker.image-retag@master
        with:
          image_name: ${{ github.repository }}
          image_old_tag: pr-${{ github.event.pull_request.number }}
          image_new_tag: latest
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Approve PR
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && success() }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}