name: Deploy Helm Chart

on:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true
      DISCORD_TOKEN:
        required: true
      GEMINI_API_KEY:
        required: true
      REDIS_STORAGE_CLASS:
        required: true
      REDIS_SUBPATH:
        required: false

jobs:
  deploy-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.0

    - name: Update Helm Dependencies
      run: helm dependency update ./charts/discord-peter

    - name: Deploy
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

        SUBPATH_ARG=""
        if [[ -n "${{ secrets.REDIS_SUBPATH }}" ]]; then
          SUBPATH_ARG="--set redis.master.persistence.subPath=${{ secrets.REDIS_SUBPATH }}"
        fi

        helm upgrade --install discord-peter ./charts/discord-peter \
          --namespace discord-peter \
          --create-namespace \
          --set image.repository=ghcr.io/${{ github.repository }} \
          --set image.tag=${{ github.sha }} \
          --set secrets.discordToken=${{ secrets.DISCORD_TOKEN }} \
          --set secrets.geminiApiKey=${{ secrets.GEMINI_API_KEY }} \
          --set redis.master.persistence.enabled=true \
          --set redis.master.persistence.storageClass=${{ secrets.REDIS_STORAGE_CLASS }} \
          --set redis.master.persistence.size=1Gi \
          --set redis.master.volumePermissions.enabled=true \
          $SUBPATH_ARG
