name: Deploy Helm Chart

on:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true
      DISCORD_TOKEN:
        required: true
      GEMINI_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Configure Kubernetes context
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        
    - name: Deploy
      run: |
        helm upgrade --install discord-peter app \
          --namespace discord-peter \
          --set image.repository=ghcr.io/${{ github.repository }} \
          --set image.tag=${{ github.sha }} \
          --set secrets.discordToken=${{ secrets.DISCORD_TOKEN }} \
          --set secrets.geminiApiKey=${{ secrets.GEMINI_API_KEY }} \
          --create-namespace
      env:
        KUBECONFIG: $(pwd)/kubeconfig.yaml
