name: Deploy Helm Chart

on:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true
      DISCORD_TOKEN:
        required: true
      GEMINI_API_KEY:
        required: true

jobs:
  deploy-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.0

    - name: Deploy
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        helm repo add discord-peter-repo https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        helm upgrade --install discord-peter discord-peter-repo/discord-peter \
          --namespace discord-peter \
          --set image.repository=ghcr.io/${{ github.repository }} \
          --set image.tag=${{ github.sha }} \
          --set secrets.discordToken=${{ secrets.DISCORD_TOKEN }} \
          --set secrets.geminiApiKey=${{ secrets.GEMINI_API_KEY }} \
          --create-namespace
