name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      KUBECONFIG:
        required: true
      DISCORD_TOKEN:
        required: true
      GEMINI_API_KEY:
        required: true
      REDIS_STORAGE_CLASS:
        required: true
      REDIS_SUBPATH:
        required: false

jobs:
  deploy-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.0

    - name: Update Helm Dependencies
      run: helm dependency update ./charts/discord-peter

    - name: Deploy
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

        helm upgrade --install discord-peter ./charts/discord-peter \
          --namespace discord-peter \
          --create-namespace \
          --set image.repository=ghcr.io/${{ github.repository }} \
          --set image.tag=${{ inputs.tag }} \
          --set secrets.discordToken=${{ secrets.DISCORD_TOKEN }} \
          --set secrets.geminiApiKey=${{ secrets.GEMINI_API_KEY }} \
          --set redis.master.persistence.enabled=true \
          --set redis.master.persistence.storageClass=${{ secrets.REDIS_STORAGE_CLASS }} \
          --set redis.master.persistence.size=1Gi \
          --set redis.master.volumePermissions.enabled=true \
          --set redis.master.persistence.subPath=${{ secrets.REDIS_SUBPATH }}
