name: Release Helm Chart

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get current chart version
        run: |
          CHART_VERSION=$(yq e '.version' charts/discord-peter/Chart.yaml)
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        with:
          args: "patch --current-version=${{ env.CHART_VERSION }}"
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"

  deploy-repo:
    needs: release-chart
    uses: ./.github/workflows/deploy-repo.yml