name: Test Dependencies

on:
  pull_request_target:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '**/.github/**/*.yml'
      - '**/charts/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Approve and merge Dependabot PR
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' && success() }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}